Fix package installation by not using shakedown. (#331)
* Fix package installation by not using shakedown.

Looks like current version of dcos-commons docker image contains a
broken version of shakedown:

```
Traceback (most recent call last):
  File "./scale-tests/deploy-dispatchers.py", line 186, in <module>
    quota_executors_mem=arguments['--quota-executors-mem'])
  File "./scale-tests/deploy-dispatchers.py", line 137, in deploy_dispatchers
    options_json=options)
  File "/usr/local/lib/python3.5/dist-packages/shakedown/dcos/package.py", line 113, in install_package
    package_manager.install_app(pkg, options, service_name)```
TypeError: install_app() takes 3 positional arguments but 4 were given
```

This change switches to using sdk_install instead.

* Make default options clearer (#332)

* Use open as argument directly.